title: "Shashank Singh"
author: "Shashank Singh"
description: "IISER <b style=\"color: #f45;\"> Bhopal </b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
paginate: 5
paginate_path: /page/:nun/

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true          # adds a grey frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
show_title: true           # always show the side title


# styling
dark_header: true
minimal: false             # use a dark header


# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", icon: home}
  - {file: "projects.md", icon: clipboard}
  - {file: "archive.html", icon: archive, title: "Archive"}
  - {file: "README.md", title: "About me", icon: address-card}
  - {file: "blog.md", title: "Blog"}
  - {file: "search.md", icon: search}
  
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:sha2nk.singh@gmail.com"}
  - {title: Github, icon: github, url: "https://drshashanksingh.github.io/homepage"}
#  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-sitemap
 
